# Dict. with field names and their units after a volume integral 
field_units = {"avg_pressure": "[J]",
                "density": "[kg]",
                "diffcoeff": "[m^5/s]",
                "DistributionMap": "[-]",
                "divu": "[m^3 / s]",
                "enstrophy": "[J]",
                "FunctCall": "[-]",
                "gradp": "[N]",
                "HeatRelease": "[W]",
                "I_R": "[kg / s]",
                "kinetic_energy": "[J]",
                "lambda": "[W m^2 / K]",
                "mag_vort": "[m^3 / s]",
                "mass_fractions": "[-]",
                "mixture_fraction": "[-]",
                "mole_fraction": "[-]",
                "progress_variable": "[-]",
                "Qcrit": "[-]",
                "rhoh": "[J]",
                "RhoRT": "[J]",
                "temp": "[K m^3]",
                "velocity": "[m^4/s]",
                "viscosity": "[J-s]",
                "volFrac": "[-]",
                "vorticity": "[m^3 / s]",
                "X": "[-]",
                "Y": "[-]",}